add MonomialIntegerPrograms package version 1.0
Macaulay2/M2 pull request #1575
Opened 2020-11-02 12:03 UTC by lilysilverstein

new package

2020-11-02 14:13 UTC, DanGrayson commented
Thank you for the contribution.  There are errors occurring while running the examples:
```m2
currentString:1:1:(3):[2]: error: installPackage: 5 error(s) occurred running examples for package MonomialIntegerPrograms
```

2020-11-02 18:40 UTC, lilysilverstein commented
Thank you Dan! As soon as I made the PR I realized it would fail testing without scip (classic case of "but it works on my computer!") but didn't remember how to fix this. Thanks for the instructions which saved me a lot of grief. Will update soon.

2020-11-03 15:05 UTC, DanGrayson requested changes

2020-11-03 15:05 UTC, DanGrayson commented on M2/Macaulay2/packages/MonomialIntegerPrograms.m2
> +  CannedExample
Why use any canned examples?  To test the code works, it would be better if it were an ordinary example, so it would get rerun from time to time.

2020-11-03 15:21 UTC, d-torrance commented on M2/Macaulay2/packages/MonomialIntegerPrograms.m2
> +userPath = MonomialIntegerPrograms#Options#Configuration#"CustomPath";
Note that `findProgram` (and its partner, `runProgram`, which could potentially be used to simplify all the various calls to `run`) weren't added until after 1.16 was released, so you'd need a relatively recent build.

I tried to be pretty thorough writing the documentation, so hopefully `help findProgram` and `help runProgram` are useful.  But I'm happy to answer any questions!

2020-11-19 17:01 UTC, DanGrayson commented
@lilysilverstein -- will you have time to update the package soon?

2020-11-30 15:13 UTC, closed without merging

2020-11-30 15:15 UTC, DanGrayson commented
oops, closed by mistake

2020-11-30 15:17 UTC, DanGrayson commented
@lilysilverstein  -- Github won't let me reopen this pull request.  Could you resubmit it (and still remember to attend to the comments here) ?

2020-12-02 10:07 UTC, lilysilverstein commented
Yes, thanks for all the pointers from yourself and Doug Torrance, which really helped me know how to go about the changes. And the patience, It shouldn't take that long, I've just had trouble finding the time. My semester ends next week and I plan to finish this up then. Is that reasonable or is there I deadline I need to worry about?

LS
________________________________
From: Daniel R. Grayson <notifications@github.com>
Sent: Monday, November 30, 2020 7:17 AM
To: Macaulay2/M2 <M2@noreply.github.com>
Cc: Lily R. Silverstein <lsilverstein@cpp.edu>; Mention <mention@noreply.github.com>
Subject: Ex: Re: [Macaulay2/M2] add MonomialIntegerPrograms package version 1.0 (#1575)


@lilysilverstein<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flilysilverstein&data=04%7C01%7Clsilverstein%40cpp.edu%7C7e236bdc34e6413d3e9f08d895431174%7C164ba61e39ec4f5d89ffaa1f00a521b4%7C0%7C0%7C637423462571093837%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Fgzkku2%2B5zILjCwKlKewDqxhSw2CTlGtaK5somMG7UE%3D&reserved=0> -- Github won't let me reopen this pull request. Could you resubmit it (and still remember to attend to the comments here) ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMacaulay2%2FM2%2Fpull%2F1575%23issuecomment-735848936&data=04%7C01%7Clsilverstein%40cpp.edu%7C7e236bdc34e6413d3e9f08d895431174%7C164ba61e39ec4f5d89ffaa1f00a521b4%7C0%7C0%7C637423462571103829%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=15aCTwWpyaWS706lPFDXPPhCVkFL%2BEaoZfc5te1WbBA%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACE6X6GGQSCXVPX3LWI3LITSSOZQ7ANCNFSM4THMGLZQ&data=04%7C01%7Clsilverstein%40cpp.edu%7C7e236bdc34e6413d3e9f08d895431174%7C164ba61e39ec4f5d89ffaa1f00a521b4%7C0%7C0%7C637423462571103829%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XZWGX6Pqx%2FgK361J2REccpnwtEK8sQBlRYDF0q2024o%3D&reserved=0>.

CAUTION: This email was not sent from a Cal Poly Pomona service. Exercise caution when clicking links or opening attachments. Please forward suspicious email to suspectemail@cpp.edu<mailto:suspectemail@cpp.edu>.

2020-12-02 12:40 UTC, DanGrayson commented
We announced a "beta" release by Dec 1 ( see https://groups.google.com/g/macaulay2/c/XFFbr8OdAe4/m/dlLjOiMPBQAJ ), but, as you can see, we're running late.  Still, even if you miss that, the final release will be a few weeks later, so you should be able to make that.