COMPILE_FLAGS in C/CXXFLAGS instead of CPPFLAGS
Macaulay2/M2 pull request #2046
Opened 2021-05-06 22:29 UTC by jpoiret

Put COMPILE_FLAGS in the corresponding C/CXXFLAGS variable, instead of CPPFLAGS which is for pre-processor flags.

This fixes a bug where when `-march=native` was in COMPILE_FLAGS (for example when BUILD_NATIVE is on), `./configure` would fail to pick up the proper architecture in the 4ti2 compilation as autoconf uses non-standard flags ordering and thus `-march=native` would shadow whatever `-march=` flag was being tested, falsifying the result, and leading to a failing compilation.

See https://savannah.gnu.org/support/?110484 for more.

2021-05-09 00:10 UTC, mahrud requested changes
If you go through `configure.cmake`, there are a number of calls like
```
  add_compile_options(-DNDEBUG -DOM_NDEBUG -DSING_NDEBUG -Wuninitialized)
```
For instance `-DSING_NDEBUG` is a no-debug flag for Factory. I'm worried that with this change Factory isn't getting this flag during preprocessing. I'm not sure what's the best solution though.

2021-05-09 10:21 UTC, jpoiret commented
You're right about that, we should modify them to use `add_compile_definitions` instead. I'll see if I can sort this out cleanly.

2021-05-09 14:48 UTC, mahrud commented
Yes, but then can we get a list of currently added definitions from cmake similar to how we can get all compile options with `COMPILE_OPTIONS`?

2021-05-12 15:32 UTC, DanGrayson commented
@jpoiret -- do you think you can get the changes completed in the next few days, in time for M2 1.18?

2021-05-12 16:00 UTC, mahrud commented
It's not a change that affects the released binaries, so I don't see a reason to rush it.

2021-05-12 16:36 UTC, DanGrayson commented
Oh, right, no rush.

2021-05-16 21:35 UTC, jpoiret commented
I've replaced `add_compile_options` with `add_compile_definitions` where applicable (I found the cppflags with a simple grep, turns out there weren't that many). I've also added the `COMPILE_DEFINITIONS` variable following what was being done with `COMPILE_OPTIONS` and `LINK_OPTIONS`. I've checked that the proper flags are passed to factory, for example.

This should be enough to properly separate pre-processor and processor flags!

2021-05-16 21:42 UTC, mahrud approved these changes

2021-05-16 21:42 UTC, mahrud commented on M2/cmake/configure.cmake
> +get_property(COMPILE_DEFINITIONS DIRECTORY PROPERTY COMPILE_DEFINITIONS)
Ah, of course. Nice fix!

2021-05-16 21:43 UTC, jpoiret commented
I should also note that in the long run, it should be better to add compile, pp and linker options per target rather than for the whole project as is possible with cmake, but this should suffice for now.

2021-05-16 22:36 UTC, mahrud commented
> I should also note that in the long run, it should be better to add compile, pp and linker options per target rather than for the whole project as is possible with cmake, but this should suffice for now.

Yes, I agree; only a few sources in the engine include headers for any given library and therefore need the preprocessor flags for that library only. Majority of sources shouldn't need more than a few generic flags.

2021-05-17 08:27 UTC, jpoiret commented
Actually, my bad, the flags are then passed to the main compilation processes as `-D-DNDEBUG` for example, which leads to the build failures highlighted above for macaulay2 itself. I'll try to fix this soon, and maybe also tie the flags to their targets.

Do you know if there's somewhere i could find which cppflag is used by which submodule?

2021-05-17 12:04 UTC, mahrud commented
> also tie the flags to their targets.

This isn't worth your time right now, and would probably make it harder to maintain the build system.

2021-05-22 08:47 UTC, jpoiret commented
Alright, this should now build properly, and pass the right CPPFLAGS to libraries and programs, sorry for the delay.

2021-05-24 13:04 UTC, merged