Varieties v0.3
Macaulay2/M2 pull request #3567
Opened 2024-11-01 08:10 UTC by mahrud

This is a repeat of #3517, which is on top of #3522 and shares a exact few commits with #3526, but I don't believe there should be a conflict.

2024-11-06 23:25 UTC, mahrud commented
@ggsmith @mikestillman is everyone happy with merging this?

2024-11-22 02:41 UTC, mahrud commented
It would be good to have this merged soon so the branch is free to continue developing on.

2024-12-04 15:08 UTC, mahrud commented
@mikestillman @ggsmith should I go ahead and merge this? We shouldn't wait until a week before the next release to merge big pull requests.

2024-12-04 16:06 UTC, mahrud commented
You had reviewed the previous PR #3517, which I accidentally closed and had to reopen. I think I've addressed all of your comments there. No other changes have been added since.

Do you have an estimate of when you could look at the details? Varieties wasn't updated in version 1.24.05 and again didn't get updated in 1.24.11. There are new features and bug fixes that Devlin and I have worked on, but I'm afraid if we continue it won't make it to 1.25 either.

2025-01-10 20:50 UTC, mikestillman commented
@mahrud I'm ready to look at your few open PR's.  I'm a bit confused about which to do in what order. 3522 first, then 3550, then 3567, then 3582?  Are there duplicate commits in these?

2025-01-10 20:54 UTC, mahrud commented
You can start from the smallest ones if you prefer, but the order they're reviewed or merged doesn't matter.

2025-02-03 20:45 UTC, Devlin-Mallory commented
@ggsmith @mikestillman Just wanted to check on this PR - it would be good to be able to continue developing the SheafMaps branch. If there's any changes that require explanation I'd be happy to discuss.

2025-02-12 04:01 UTC, mahrud commented on M2/Macaulay2/m2/modules2.m2
> +pushout List := Module => applyUniformMethod(symbol pushout, "pushout")
Yes, there are lots of things not documented. (To be clear, pushout/pullback didn't exist in the Core before we added them for Varieties in the last PR)

2025-02-12 04:03 UTC, mahrud commented on M2/Macaulay2/m2/shared.m2
> +isAbelianCategory = method(TypicalValue => Boolean)
It would be interesting, especially if this worked for other types of modules (e.g. quiver representations), but I was trying to do the minimal absolute necessary changes to get complexes of sheaves.

2025-02-12 04:04 UTC, mahrud commented on M2/Macaulay2/packages/Varieties.m2
>  AffineVariety     **     AffineVariety :=     AffineVariety => (X, Y) -> Spec(ring X ** ring Y)
"Spec" will ignore the (multi)grading.

2025-02-12 04:05 UTC, mahrud commented on M2/Macaulay2/packages/Varieties.m2
> +sheaf Ring := Ring^~ := SheafOfRings =>     R  -> sheaf(variety R, R)
Not until we remove this in a future release:
```m2
-- TODO: remove by M2 1.25
tildeWarn = true
Thing~ := x -> (if tildeWarn then (tildeWarn = false; printerr "Note: M~ is deprecated; use M^~ or sheaf instead."); x^~)
```

2025-02-12 16:10 UTC, mahrud commented on M2/Macaulay2/packages/Varieties/SheafComplexes.m2
> +euler Complex := C -> sum(-length C .. length C, i -> (-1)^i * euler C_i)
No, this was a typo from the previous version. I'll fix it.

2025-02-12 16:17 UTC, mahrud commented on M2/Macaulay2/packages/Varieties/doc-complexes.m2
> +    eulerSequence
Produces the Euler sequence as a complex of sheaves.

2025-02-12 16:22 UTC, mahrud commented on M2/Macaulay2/packages/Macaulay2Doc/functions/quotient-remainder-doc.m2
> +        scalar matrix acting on @TT "H"@. If @TT "g"@ is a @TO "MonomialIdeal"@,
Good question. This is identically moved here from the documentation of Matrix // Matrix. In particular, the typo is present in the [current version](https://macaulay2.com/doc/Macaulay2/share/doc/Macaulay2/Macaulay2Doc/html/___Matrix_sp_sl_sl_sp__Matrix.html).

2025-02-12 16:25 UTC, mahrud commented
@mikestillman could you clarify which of your comments are things you want changed before this is merged and which are suggestions for future? Unless others want to contribute, the documentation suggestions are not going to happen in this PR.

2025-02-12 17:40 UTC, Devlin-Mallory commented on M2/Macaulay2/packages/Varieties.m2
> +pdim    CoherentSheaf := F -> tryHooks((pdim,  CoherentSheaf), F, pdim  @@ module)
(Not really related to Varieties, but inspired by this discussion I made an issue (#3656) about pdim for modules.)

2025-02-12 17:45 UTC, Devlin-Mallory commented on M2/Macaulay2/packages/Varieties/doc-varieties.m2
> +      defines a reduced object.
I guess the point is that there is a "natural" scheme structure on the singular locus, and saturating gives you the saturated homogeneous ideal defining this natural (potentially nonreduced) scheme structure locally. But I can't imagine that most people using this care about the scheme structure rather than just its support, so perhaps the default in a future version should be to just give *an* ideal defining the singular locus without bothering to saturate.

2025-02-24 20:53 UTC, mikestillman commented on M2/Macaulay2/packages/Varieties/SheafComplexes.m2
> +freeResolution Complex := Complex => opts -> C -> resolution(C, opts)
This code should be reviewed when SheafComplexes is made active.

2025-02-24 21:30 UTC, mikestillman commented on M2/Macaulay2/packages/Varieties/doc-maps.m2
> +    }
Why are these undocumented?

2025-02-24 21:38 UTC, mikestillman commented on M2/Macaulay2/packages/Varieties/doc-sheaves.m2
> +--    (isWellDefined, Module)
What is actually checked here?

2025-02-24 21:40 UTC, mikestillman commented on M2/Macaulay2/packages/Varieties/doc-varieties.m2
> +      defines a reduced object.
In many cases, this function doesn't finish in reasonable time, so I rarely use it myself... (I'm talking about before your changes).

2025-02-25 01:25 UTC, mikestillman commented on M2/Macaulay2/tests/normal/quotientRemainder.m2
>  end
Here is another test for left and right quotients.  Can you add this in (or something like it?)
```
S = ZZ/101[a..d]/(a^2+b^2+c^2+d^2)
F = res(coker vars S, LengthLimit => 10)
A = coker F.dd_4
B = coker F.dd_3
C = coker F.dd_5
HAB = Hom(A,B)
basis(0, HAB)
f = homomorphism(basis(0, HAB) * random(S^48, S^1))
HBC = Hom(B,C)
basis(3, HBC)
gd = homomorphism(basis(3, HBC) * random(S^32, S^1))
g = map(target gd ** S^{3}, source gd, gd)
degree g == {0} and isHomogeneous g
h = g*f
-- So: f : A --> B
--     g : B --> C ** S^{3}
--     h : A --> C ** S^{3}
assert(g * (h//g) == h)
assert(h // g == f) 
assert(f \\ h == g)
assert((f\\h) * f == h)
g // h == 0. -- does it always happen that this is zero if lift can't occur?  Probably not
h \\ f == 0
```

2025-02-25 01:54 UTC, mikestillman requested changes
This looks good, and is a much needed improvement!  I like what the next plan is as well, adding Complexes of sheaves.  The depth of functionaity is far more useful than previously.  Thanks!

I placed a comment into the code/review about a test of //, \\ which involves non-trivial (I think) modules.  It worked great.  As we don't seem to have any examples with non-free modules, I think it would be good to add this in, or something along these lines, depending what you prefer. (I'll let you do that, hopefully you will see the test I created).

Additionally, I was looking at some of the doc for the package, that might have been added earlier, and there are some inaccuracies in the doc (e.g. for (minimalPresentation, CoherentSheaf)).  @mahrud maybe we can discuss that in person sometime this week, maybe tomorrow (Tuesday)?  The doc that is here is much improved over the essentially non-existent doc from before, but some things should be fixed.

There are also a number of other doc nodes that appear incomplete.  My guess is that you plan on adding those, but will do that in a (hopefully near) upcoming PR? 

After these comments are handled in some form, this PR is ready to be merged.  Sorry that it has taken me so long to handle this.

2025-02-26 04:36 UTC, mahrud commented on M2/Macaulay2/tests/normal/quotientRemainder.m2
>  end
Btw, I'm about to add a commit that lets you just do `homomorphism random HAB`.

2025-02-26 04:37 UTC, mahrud commented on M2/Macaulay2/packages/Varieties/doc-sheaves.m2
> +--    (isWellDefined, Module)
Various data structure things (e.g. correct keys in the hash table), compatible rings, homogeneity of the module if the variety is projective, and maybe more in the future.

2025-02-26 04:40 UTC, mahrud commented on M2/Macaulay2/packages/Varieties/doc-maps.m2
> +    }
Mainly because nobody got around to it, but if people are already familiar with the same operation with matrices, is there a point in repeating them? I think having a tutorial that covers a bunch of things like this is more useful than documenting each small part of the parlance.

2025-02-26 04:45 UTC, mahrud commented on M2/Macaulay2/tests/normal/quotientRemainder.m2
>  end
Thanks for the test, added it now.

2025-03-03 16:58 UTC, mahrud commented
@mikestillman I implemented the main suggestions and added the new test. Let me know if anything else should be done now.

2025-03-07 18:24 UTC, mikestillman commented
Where are the fixes and changes?  I can't find them, after the rebase?  Once I see them, I will likely approve this.

2025-03-07 18:25 UTC, mikestillman commented
OK, I found the test that you added.  Can you point me to code that was modified since last week?  I just want to quickly look at the changes.

2025-03-12 01:30 UTC, mahrud commented
Argh another conflict ... I'll have to do another rebase, but the changes will be just what I showed you today.

2025-03-12 20:27 UTC, mahrud commented
@d-torrance I just rebased this; how is it still having conflicts?

2025-03-13 01:05 UTC, mikestillman commented on M2/Macaulay2/m2/genmat.m2
> +    if isHomogeneous M then random(degree 1_(ring M), M, o) else localRandom(M, o))
If the module is finite length (possibly a common use), will the localRandom routine be efficient for that case?

2025-03-13 01:34 UTC, mikestillman commented on M2/Macaulay2/m2/genmat.m2
> +    if isHomogeneous M then random(degree 1_(ring M), M, o) else localRandom(M, o))
This is my last comment for this pull request (I think!).

2025-03-13 01:45 UTC, mahrud commented on M2/Macaulay2/m2/genmat.m2
> +    if isHomogeneous M then random(degree 1_(ring M), M, o) else localRandom(M, o))
You can get the output you prefer with `localRandom image basis M`

I don't know what you mean by efficient. Certainly our main application input of interest, which are endomorphism algebras, are finite dimensional, and this seems to work well. Given that the output of `random` for your example also gives a constant element, I think what you want probably should be called something else? Or you just need to type the extra `image basis`?

2025-03-13 01:54 UTC, mikestillman commented on M2/Macaulay2/m2/genmat.m2
> +    if isHomogeneous M then random(degree 1_(ring M), M, o) else localRandom(M, o))
True.  But my question was more about what is correct mathematically.  I'm not sure what the answer is, except in the random(d,M) case, and the case when M is finite over the base ring.  In the local case, how would you characterize mathematically what it gives now, and why is it called "local"?  Is it just a random sum over the base ring of the generators of M?

2025-03-13 03:58 UTC, mahrud commented on M2/Macaulay2/m2/genmat.m2
> +    if isHomogeneous M then random(degree 1_(ring M), M, o) else localRandom(M, o))
Yes, that's exactly what the code is doing, and I think for a _module_ this is the reasonable thing to do (especially given that in special situations like finite length modules one can easily do `random image basis M`).

Here's an example that justifies the "local" part:
```m2
R = ZZ/101[x,y]
M = image matrix {{x+x^2, y+y^2}}
random M -- e.g. | -3x2+17y2-3x+17y |
```
Note that it's combining the columns

2025-03-13 15:10 UTC, Devlin-Mallory commented on M2/Macaulay2/m2/genmat.m2
> +    if isHomogeneous M then random(degree 1_(ring M), M, o) else localRandom(M, o))
@mikestillman I agree that it's not obvious mathematically what random should do in the non-graded case, but I think "random sum over the base ring of the generators of M" is the most *useful* choice (thus coinciding with random(min degrees M,M) in the graded case). 

In the local case, the mathematical point of view is that random(M) is lifting a random element of the (finite) vector space M/mM to an element of M. That lift depends on the choice of generators of M, of course, but the image in M/mM does not.

2025-03-14 16:53 UTC, merged

2025-05-08 14:09 UTC, mahrud commented
I think just that it has been updated? Unless someone else can dig through specific new features to mention. The documentation is still lacking, so users wouldn't necessarily be able to find out what new things are possible.